[[ "$(uname -s)" == "Darwin" ]] && . ~/.dotfiles/zsh/osx.zsh
[[ "$(uname -s)" == "Linux" ]] && . ~/.dotfiles/zsh/linux.zsh

[[ -d /usr/local/lib ]] && export LD_LIBRARY_PATH="/usr/local/lib"
[[ -d ${HOME}/.dotfiles/scripts ]] && export PATH="${HOME}/.dotfiles/scripts:${PATH}"

# add SSH keys
KEYS=$(find ${HOME}/.ssh -name id_dsa -or -name id_rsa)
[[ -z $(pidof ssh-agent) ]] && echo ${KEYS} | xargs ssh-add > /dev/null 2>&1

# make SSH key forwarding work in screen and tmux
AGENT=/tmp/ssh-agent-tmux-${USER}
test "${SSH_AUTH_SOCK}" && [[ "${SSH_AUTH_SOCK}" != "${AGENT}" ]] && ln -sf "${SSH_AUTH_SOCK}" "${AGENT}"
test "$TMUX" && export SSH_AUTH_SOCK="${AGENT}"
unset AGENT

# set up terminal colors properly
[[ "${TERM}" == "xterm" ]] && export TERM=xterm-256color

export ACK_PAGER=less
export EDITOR=vim

alias diff='colordiff'
alias vi='vim -p'
alias vim='vim -p'
alias gvim='gvim -p'
alias mvn='mvn-color'

# Google Cloud SDK
if [[ -d /usr/local/gcloud/google-cloud-sdk ]]; then
    source '/usr/local/gcloud/google-cloud-sdk/path.zsh.inc'
    source '/usr/local/gcloud/google-cloud-sdk/completion.zsh.inc'
    alias gscat='gsutil cat'
    alias gscp='gsutil -m cp'
    alias gsdu='gsutil du'
    alias gsls='gsutil ls'
    alias gsmv='gsutil -m mv'
    alias gsrm='gsutil -m rm'
fi

if type hub > /dev/null; then
    alias g='hub'
    compdef hub=git
fi

# Restrict git completion to local files
__git_files () {
    _wanted files expl "local files" _files
}


if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    [[ "$(uname -s)" == "Darwin" ]] && export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
    source /usr/local/bin/virtualenvwrapper.sh
    WORKON_HOME=${HOME}/src/virtualenv
fi
# autoenv
[[ -f /usr/local/bin/activate.sh ]] && source /usr/local/bin/activate.sh

[ -d $HOME/.rbenv ] && eval "$(rbenv init -)"

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# vim: ft=zsh:
