[theme]
name = "dracula"

[keys] # Match tmux
prefix = "backtick"
detach = "prefix+d"
settings = "prefix+comma" # Free up prefix-s
split_horizontal = "prefix+s" # Default
split_vertical = "prefix+v"
# Same direction on Keyboardio, {} vs fn + jk
previous_workspace = "prefix+{"
next_workspace = "prefix+}"
previous_agent = "prefix+down"
next_agent = "prefix+up"
previous_tab = "prefix+p" # Default
next_tab = "prefix+n" # Default

[ui]
prompt_new_tab_name = false
prompt_new_workspace_name = true
pane_gaps = false
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = false
