onboarding = false

[theme]
name = "dracula"

[keys] # Match tmux
prefix = "backtick"
detach = "prefix+d"
settings = "prefix+comma" # Free up prefix-s
split_horizontal = "prefix+s" # Default
split_vertical = "prefix+v"
previous_workspace = "prefix+left"
next_workspace = "prefix+right"
previous_agent = "prefix+up"
next_agent = "prefix+down"
previous_tab = "prefix+p" # Default
next_tab = "prefix+n" # Default

[[keys.command]]
key = "prefix+shift+h"
type = "shell"
command = "herdr pane swap --current --direction left"

[[keys.command]]
key = "prefix+shift+j"
type = "shell"
command = "herdr pane swap --current --direction down"

[[keys.command]]
key = "prefix+shift+k"
type = "shell"
command = "herdr pane swap --current --direction up"

[[keys.command]]
key = "prefix+shift+l"
type = "shell"
command = "herdr pane swap --current --direction right"

[ui]
prompt_new_tab_name = false
prompt_new_workspace_name = true
pane_gaps = false
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = false
