#!/bin/bash

die () {
    echo $1
    exit 1
}

status=$(git status --porcelain --untracked-files=no)
[ -z "${status}" ] || die "You have unstaged changes."

current=$(git symbolic-ref HEAD | sed -e 's/^refs\/heads\///')
case "$current" in
    master)
        target="testing"
        ;;
    testing)
        target="stable"
        ;;
    stable)
        die "You are already on stable branch."
        ;;
    *)
        die "Unrecognized branch ${current}."
        ;;
esac

read -n 1 -s -p "Stablize branch [${current}] to [${target}] now (y/n)?"
echo
[ ${REPLY} != "y" ] && die "die"

git pull
git checkout ${target}
git pull
git merge ${current}
git push
git checkout ${current}
