#!/bin/bash

# push branch
dest=origin
if [ $# -ge 1 ]; then
    dest=$1
fi
base=master
if [ $# -eq 2 ]; then
    base=$2
fi

src=$(git symbolic-ref HEAD | sed -e 's/^refs\/heads\///')
git push -u ${dest} ${src}
hub pull-request -b ${base}
