#!/bin/bash

# stablize master -> testing -> stable

die () {
    echo "Error: $1"
    exit 1
}

git_or_die() {
    git $* || die "failed to invoke command: git $*"
}

stablize() {
    status=$(git status --porcelain --untracked-files=no)
    [ -z "${status}" ] || die "You have unstaged changes."

    src=$(git symbolic-ref HEAD | sed -e 's/^refs\/heads\///')
    case "$src" in
        master)
            dst="testing"
            ;;
        testing)
            dst="stable"
            ;;
        stable)
            die "You are already on stable branch."
            ;;
        *)
            die "Unrecognized branch ${src}."
            ;;
    esac

    read -n 1 -s -p "Stablize branch [${src}] to [${dst}] now (y/n)?"
    echo
    [ ${REPLY} != "y" ] && die "Aborted"

    git_or_die pull
    git_or_die push
    git_or_die checkout ${dst}
    git_or_die pull
    git_or_die merge ${src}
    git_or_die push
    git_or_die checkout ${src}
}

if [ $# -eq 0 ]; then
    stablize
elif [ $# -eq 1 ]; then
    src=$1
    if [ ${src} != "master" ] && [ ${src} != "testing" ]; then
        die "stablizing unsupported branch ${src}"
    fi

    current=$(git symbolic-ref HEAD | sed -e 's/^refs\/heads\///')
    git_or_die checkout ${src}
    stablize
    git_or_die checkout ${current}
fi
