return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    main = 'nvim-treesitter.configs',
    opts = {
      ensure_installed = {
        'bash',
        'c',
        'cpp',
        'dockerfile',
        'go',
        'java',
        'javascript',
        'kotlin',
        'lua',
        'markdown',
        'python',
        'rust',
        'scala',
        'sql',
        'terraform',
        'typescript',
        'vim',
      },
      sync_install = false,
      highlight = { enable = true },
      incremental_selection = { enable = true },
      indent = { enable = true },
    },
  },
}
