return {
  {
    'nvim-treesitter/nvim-treesitter',
    branch = 'master',
    lazy = false,
    build = ':TSUpdate',
    opts = {
      ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'diff',
        'dockerfile',
        'go',
        'java',
        'javascript',
        'html',
        'kotlin',
        'lua',
        'markdown',
        'proto',
        'python',
        'rust',
        'scala',
        'sql',
        'swift',
        'terraform',
        'toml',
        'typescript',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
      },
      auto_install = true,
      highlight = { enable = true },
      incremental_selection = { enable = true },
      indent = { enable = true },
      sync_install = false,
    },
  },
}
